Remaster of the Panel API part.
SquareGPS/navixy-api pull request #70
Opened 2021-03-03 19:42 UTC by Astarsys

- Added descriptions
- Added examples
- Added meta descriptions
- Removed / from call titles
- Added parameters to tables

2021-03-04 19:02 UTC, fenik17 requested changes
Big job. Respect.

2021-03-04 19:02 UTC, fenik17 commented on docs/panel-api/resources/user.md
> +API path: `/user`.
`/panel/user`

2021-03-05 21:41 UTC, Astarsys commented
Thank you

2021-03-10 15:52 UTC, fenik17 requested changes

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/dealer/activation_code.md
> +
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/dealer/index.md
> +
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/dealer/password.md
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/subpaas/index.md
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/subpaas/index.md
> +
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/subpaas/index.md
> +
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/subpaas/password.md
Missed ```

2021-03-10 15:52 UTC, fenik17 commented on docs/panel-api/resources/subpaas/session.md
> +
Missed ```

2021-03-10 18:11 UTC, fenik17 approved these changes

2021-03-10 18:12 UTC, merged