New how-tos
SquareGPS/navixy-api pull request #73
Opened 2021-03-30 23:11 UTC by Astarsys

2021-04-02 19:52 UTC, fenik17 requested changes

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +API request:
Add internal reference to API resource `/status/listing/create`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-send-commands-to-device.md
> +API request:
Add internal reference to API resource `tracker/raw_command/send`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +API request:
Add internal reference to API resource `/status/create`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +API request:
Add internal reference to API resource `/status/listing/tracker/assign`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +        -d '{"hash": "22eac1c27af4be7b9d04da2ce1af111b", "tracker_id": "615487", "listing_id": "111"}'
`listing_id` and `tracker_id` is not a string

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +        -d '{"hash": "22eac1c27af4be7b9d04da2ce1af111b", "listing_id": "1111", "status": {"label": "Free", "color": "E57373"}}'
`listing_id` is not a string

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-send-commands-to-device.md
> +        -d '{"hash": "a6aa75587e5c59c32d347da438505fc3", "tracker_id": "231402", "command": "setparam 2004:52.57.1.136"}'
`tracker_id` is not a string

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +will change the status itself to "Pick up the goods from storage."
A dot at the end should be out of quotes.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-statuses.md
> +We can create a script that will assign a new task to a driver with the status "Free." After assigning the task, this script
A dot at the end should be out of quotes.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-tasks.md
> +API request:
Add internal reference to API resource `/task/create`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-tasks.md
> +id 120945. He can't get late because our customers will wait for production at the exact time and if he is late - the checkpoint
Should this tracker id used in the cURL example?

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-tasks.md
> +* `external_id` - this is a delivery code. It is necessary for a checkpoint because I have the plugin "Courier on the map."
A dot at the end should be out of quotes.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-tasks.md
> +API request:
Add internal reference to API resource `/task/route/create`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to-work-with-tasks.md
> +API request:
Add internal reference to API resource `/task/route/points/optimize`.

2021-04-02 19:52 UTC, fenik17 commented on docs/backend-api/how-to/how-to.md
> +* [How to create, assign and read status of tasks](./how-to-work-with-tasks.md)
Maybe: "How to create/assign the tasks and optimize route"?

2021-04-07 11:23 UTC, Astarsys commented
ready

2021-04-07 11:52 UTC, fenik17 approved these changes

2021-04-07 11:52 UTC, merged